-- Supabase setup for the OCR Bet Tracker app.
-- Run this in the Supabase SQL Editor for the project used by .env.local.

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  image_url text not null,
  match_count integer not null default 0 check (match_count >= 0),
  total_odds numeric(10, 2) not null default 0 check (total_odds >= 0),
  status text not null default 'pending' check (status in ('pending', 'won', 'lost'))
);

create index if not exists tickets_created_at_idx on public.tickets (created_at desc);
create index if not exists tickets_user_id_created_at_idx on public.tickets (user_id, created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where user_id = auth.uid()
  );
$$;

alter table public.admins enable row level security;
alter table public.tickets enable row level security;

drop policy if exists "Admins are readable by their owner" on public.admins;
create policy "Admins are readable by their owner"
on public.admins
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Admins can manage admins" on public.admins;
create policy "Admins can manage admins"
on public.admins
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Authenticated users can read all tickets" on public.tickets;
create policy "Authenticated users can read all tickets"
on public.tickets
for select
to authenticated
using (true);

drop policy if exists "Users can create their own tickets" on public.tickets;
create policy "Users can create their own tickets"
on public.tickets
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Admins can update tickets" on public.tickets;
create policy "Admins can update tickets"
on public.tickets
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete tickets" on public.tickets;
create policy "Admins can delete tickets"
on public.tickets
for delete
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('tickets_images', 'tickets_images', true)
on conflict (id) do update set public = true;

drop policy if exists "Ticket images are readable" on storage.objects;
create policy "Ticket images are readable"
on storage.objects
for select
to authenticated
using (bucket_id = 'tickets_images');

drop policy if exists "Users can upload ticket images" on storage.objects;
create policy "Users can upload ticket images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'tickets_images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
  )
);

drop policy if exists "Users and admins can update ticket images" on storage.objects;
create policy "Users and admins can update ticket images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'tickets_images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
  )
)
with check (
  bucket_id = 'tickets_images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
  )
);

drop policy if exists "Users and admins can delete ticket images" on storage.objects;
create policy "Users and admins can delete ticket images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'tickets_images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
  )
);

-- After creating your first admin user in Authentication, run this with that user's UUID:
-- insert into public.admins (user_id) values ('00000000-0000-0000-0000-000000000000');
